import { Client } from './type';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1 (555) 123-4567',
    company_name: 'Fitness First LLC',
    address: '123 Main Street',
    city: 'New York',
    country: 'USA',
    budget: 5000,
    preferences: 'Morning sessions, HIIT workouts',
    notes: 'Prefers 7am slots on weekdays',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-11-20T14:30:00Z',
    totalValue: 2450.00,
    bookingsCount: 24,
    status: 'active',
    totalSessions: 30,
    sessionsUsed: 18,
    sessionsRemaining: 12,
    allergies: 'Latex',
    deals: [
      { id: '1', name: 'Premium Package', value: 1500, status: 'closed' },
      { id: '2', name: 'Monthly Subscription', value: 950, status: 'closed' },
    ],
    client_notes: [
      { id: '1', note: 'Client prefers early morning sessions before work.', created_at: '2024-11-15T08:00:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
      { id: '2', note: 'Increased weight on squats by 10lbs this week.', created_at: '2024-11-18T09:30:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
    ],
    bookings: [
      { id: 'b1', title: 'HIIT Session', schedule_date: '2025-01-10', start_time: '07:00', end_time: '08:00', status: 'scheduled', description: 'High intensity interval training' },
      { id: 'b2', title: 'Strength Training', schedule_date: '2025-01-08', start_time: '07:00', end_time: '08:00', status: 'scheduled', description: 'Upper body focus' },
      { id: 'b3', title: 'Cardio Session', schedule_date: '2024-12-01', start_time: '07:00', end_time: '08:00', status: 'completed', session_notes: 'Great progress!' },
    ],
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 234-5678',
    company_name: 'Chen Enterprises',
    address: '456 Oak Avenue',
    city: 'Los Angeles',
    country: 'USA',
    budget: 3500,
    preferences: 'Evening sessions, Strength training',
    notes: 'Has previous shoulder injury',
    createdAt: '2024-02-20T09:00:00Z',
    updatedAt: '2024-11-18T11:15:00Z',
    totalValue: 1850.50,
    bookingsCount: 18,
    status: 'active',
    totalSessions: 20,
    sessionsUsed: 15,
    sessionsRemaining: 5,
    allergies: '',
    deals: [
      { id: '3', name: 'Personal Training', value: 1200, status: 'closed' },
      { id: '4', name: 'Nutrition Plan', value: 650.50, status: 'closed' },
    ],
    client_notes: [
      { id: '3', note: 'Be careful with shoulder exercises - previous injury.', created_at: '2024-10-05T14:00:00Z', created_by: 'user_2', profiles: { first_name: 'Sarah', last_name: 'Coach' } },
    ],
    bookings: [
      { id: 'b4', title: 'Strength Training', schedule_date: '2025-01-12', start_time: '18:00', end_time: '19:00', status: 'scheduled', description: 'Lower body focus' },
      { id: 'b5', title: 'Recovery Session', schedule_date: '2024-11-28', start_time: '18:00', end_time: '19:00', status: 'completed' },
    ],
  },
  {
    id: '3',
    name: 'Emma Williams',
    email: 'emma.w@email.com',
    phone: '+1 (555) 345-6789',
    company_name: '',
    address: '789 Pine Road',
    city: 'Chicago',
    country: 'USA',
    budget: 2000,
    preferences: 'Yoga, Pilates',
    notes: 'Looking to improve flexibility',
    createdAt: '2024-03-10T14:00:00Z',
    updatedAt: '2024-11-15T09:45:00Z',
    totalValue: 980.00,
    bookingsCount: 12,
    status: 'active',
    totalSessions: 15,
    sessionsUsed: 10,
    sessionsRemaining: 5,
    allergies: 'Pollen, Dust',
    deals: [
      { id: '5', name: 'Yoga Package', value: 980, status: 'closed' },
    ],
    client_notes: [
      { id: '4', note: 'Flexibility has improved significantly over 3 months.', created_at: '2024-11-10T10:00:00Z', created_by: 'user_3', profiles: { first_name: 'Lisa', last_name: 'Yoga' } },
      { id: '5', note: 'Interested in trying meditation classes.', created_at: '2024-11-12T11:30:00Z', created_by: 'user_3', profiles: { first_name: 'Lisa', last_name: 'Yoga' } },
    ],
    bookings: [
      { id: 'b6', title: 'Yoga Session', schedule_date: '2025-01-15', start_time: '10:00', end_time: '11:00', status: 'scheduled' },
      { id: 'b7', title: 'Pilates Class', schedule_date: '2024-12-05', start_time: '10:00', end_time: '11:00', status: 'completed' },
    ],
  },
  {
    id: '4',
    name: 'James Rodriguez',
    email: 'j.rodriguez@email.com',
    phone: '+1 (555) 456-7890',
    company_name: 'Rodriguez & Co',
    address: '321 Elm Street',
    city: 'Miami',
    country: 'USA',
    budget: 4000,
    preferences: 'Boxing, Cardio',
    notes: 'Training for charity marathon',
    createdAt: '2024-04-05T08:30:00Z',
    updatedAt: '2024-11-22T16:00:00Z',
    totalValue: 3200.75,
    bookingsCount: 32,
    status: 'active',
    totalSessions: 40,
    sessionsUsed: 28,
    sessionsRemaining: 12,
    allergies: '',
    deals: [
      { id: '6', name: 'Boxing Training', value: 2000, status: 'closed' },
      { id: '7', name: 'Marathon Prep', value: 1200.75, status: 'closed' },
    ],
    client_notes: [
      { id: '6', note: 'Marathon is in March - increase cardio intensity.', created_at: '2024-11-20T08:00:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
    ],
    bookings: [
      { id: 'b8', title: 'Boxing Session', schedule_date: '2025-01-08', start_time: '06:00', end_time: '07:30', status: 'scheduled' },
      { id: 'b9', title: 'Marathon Training', schedule_date: '2025-01-11', start_time: '06:00', end_time: '08:00', status: 'scheduled' },
      { id: 'b10', title: 'Cardio Session', schedule_date: '2024-11-25', start_time: '06:00', end_time: '07:00', status: 'completed' },
    ],
  },
  {
    id: '5',
    name: 'Olivia Brown',
    email: 'olivia.brown@email.com',
    phone: '+1 (555) 567-8901',
    company_name: '',
    address: '654 Maple Lane',
    city: 'Seattle',
    country: 'USA',
    budget: 1500,
    preferences: 'Swimming, Low-impact exercises',
    notes: 'Recovering from knee surgery',
    createdAt: '2024-05-12T11:00:00Z',
    updatedAt: '2024-10-30T10:20:00Z',
    totalValue: 750.00,
    bookingsCount: 8,
    status: 'inactive',
    totalSessions: 10,
    sessionsUsed: 10,
    sessionsRemaining: 0,
    allergies: 'Chlorine sensitivity',
    deals: [
      { id: '8', name: 'Recovery Program', value: 750, status: 'closed' },
    ],
    client_notes: [
      { id: '7', note: 'Completed recovery program successfully. Ready for regular sessions.', created_at: '2024-10-28T15:00:00Z', created_by: 'user_4', profiles: { first_name: 'Dr. Mike', last_name: 'Physio' } },
    ],
    bookings: [
      { id: 'b11', title: 'Recovery Session', schedule_date: '2024-10-25', start_time: '14:00', end_time: '15:00', status: 'completed', session_notes: 'Final recovery session' },
    ],
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david.kim@email.com',
    phone: '+1 (555) 678-9012',
    company_name: 'Kim Tech Solutions',
    address: '987 Cedar Boulevard',
    city: 'San Francisco',
    country: 'USA',
    budget: 6000,
    preferences: 'Personal training, Nutrition coaching',
    notes: 'VIP client - flexible scheduling',
    createdAt: '2024-06-01T07:00:00Z',
    updatedAt: '2024-11-21T13:45:00Z',
    totalValue: 5400.00,
    bookingsCount: 45,
    status: 'active',
    totalSessions: 50,
    sessionsUsed: 38,
    sessionsRemaining: 12,
    allergies: '',
    deals: [
      { id: '9', name: 'VIP Package', value: 3500, status: 'closed' },
      { id: '10', name: 'Nutrition Coaching', value: 1900, status: 'closed' },
    ],
    client_notes: [
      { id: '8', note: 'VIP client - always accommodate schedule changes.', created_at: '2024-06-01T08:00:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
      { id: '9', note: 'Nutrition plan updated for Q4 goals.', created_at: '2024-10-01T09:00:00Z', created_by: 'user_5', profiles: { first_name: 'Amy', last_name: 'Nutritionist' } },
      { id: '10', note: 'Lost 5kg this quarter - excellent progress!', created_at: '2024-11-15T10:00:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
    ],
    bookings: [
      { id: 'b12', title: 'Personal Training', schedule_date: '2025-01-09', start_time: '12:00', end_time: '13:00', status: 'scheduled' },
      { id: 'b13', title: 'Nutrition Consultation', schedule_date: '2025-01-16', start_time: '11:00', end_time: '12:00', status: 'scheduled' },
      { id: 'b14', title: 'Personal Training', schedule_date: '2024-12-02', start_time: '12:00', end_time: '13:00', status: 'completed' },
    ],
  },
  {
    id: '7',
    name: 'Sophie Martinez',
    email: 'sophie.m@email.com',
    phone: '+1 (555) 789-0123',
    company_name: '',
    address: '147 Birch Street',
    city: 'Austin',
    country: 'USA',
    budget: 2500,
    preferences: 'Group classes, Zumba',
    notes: 'Enjoys social workout environments',
    createdAt: '2024-07-18T15:30:00Z',
    updatedAt: '2024-11-19T08:10:00Z',
    totalValue: 1200.00,
    bookingsCount: 15,
    status: 'active',
    totalSessions: 20,
    sessionsUsed: 12,
    sessionsRemaining: 8,
    allergies: 'Shellfish',
    deals: [
      { id: '11', name: 'Group Classes Bundle', value: 1200, status: 'closed' },
    ],
    client_notes: [
      { id: '11', note: 'Loves the Tuesday Zumba class - always attends.', created_at: '2024-09-10T17:00:00Z', created_by: 'user_6', profiles: { first_name: 'Maria', last_name: 'Zumba' } },
    ],
    bookings: [
      { id: 'b15', title: 'Zumba Class', schedule_date: '2025-01-14', start_time: '18:00', end_time: '19:00', status: 'scheduled' },
      { id: 'b16', title: 'Group Fitness', schedule_date: '2024-11-26', start_time: '18:00', end_time: '19:00', status: 'completed' },
    ],
  },
  {
    id: '8',
    name: 'Robert Taylor',
    email: 'r.taylor@email.com',
    phone: '+1 (555) 890-1234',
    company_name: 'Taylor Industries',
    address: '258 Walnut Drive',
    city: 'Denver',
    country: 'USA',
    budget: 3000,
    preferences: 'CrossFit, Functional training',
    notes: 'Competitive athlete background',
    createdAt: '2024-08-22T12:00:00Z',
    updatedAt: '2024-09-15T17:30:00Z',
    totalValue: 600.00,
    bookingsCount: 6,
    status: 'inactive',
    totalSessions: 10,
    sessionsUsed: 6,
    sessionsRemaining: 4,
    allergies: '',
    deals: [
      { id: '12', name: 'CrossFit Intro', value: 600, status: 'closed' },
      { id: '13', name: 'Advanced Training', value: 1500, status: 'pending' },
    ],
    client_notes: [
      { id: '12', note: 'Client on hold - traveling for work until January.', created_at: '2024-09-15T17:00:00Z', created_by: 'user_1', profiles: { first_name: 'John', last_name: 'Trainer' } },
    ],
    bookings: [
      { id: 'b17', title: 'CrossFit Session', schedule_date: '2024-09-10', start_time: '07:00', end_time: '08:00', status: 'completed' },
    ],
  },
  {
    id: '9',
    name: 'Isabella Garcia',
    email: 'isabella.g@email.com',
    phone: '+1 (555) 901-2345',
    company_name: 'Garcia Wellness',
    address: '369 Spruce Court',
    city: 'Phoenix',
    country: 'USA',
    budget: 4500,
    preferences: 'Meditation, Yoga, Wellness coaching',
    notes: 'Holistic approach to fitness',
    createdAt: '2024-09-05T09:15:00Z',
    updatedAt: '2024-11-23T11:00:00Z',
    totalValue: 2800.25,
    bookingsCount: 22,
    status: 'active',
    totalSessions: 25,
    sessionsUsed: 18,
    sessionsRemaining: 7,
    allergies: 'Essential oils (lavender)',
    deals: [
      { id: '14', name: 'Wellness Package', value: 1800.25, status: 'closed' },
      { id: '15', name: 'Meditation Course', value: 1000, status: 'closed' },
    ],
    client_notes: [
      { id: '13', note: 'Avoid lavender oils during sessions.', created_at: '2024-09-05T10:00:00Z', created_by: 'user_3', profiles: { first_name: 'Lisa', last_name: 'Yoga' } },
      { id: '14', note: 'Completed meditation course with flying colors.', created_at: '2024-11-20T16:00:00Z', created_by: 'user_3', profiles: { first_name: 'Lisa', last_name: 'Yoga' } },
    ],
    bookings: [
      { id: 'b18', title: 'Meditation Session', schedule_date: '2025-01-13', start_time: '09:00', end_time: '10:00', status: 'scheduled' },
      { id: 'b19', title: 'Yoga Session', schedule_date: '2025-01-10', start_time: '09:00', end_time: '10:00', status: 'scheduled' },
      { id: 'b20', title: 'Wellness Consultation', schedule_date: '2024-11-22', start_time: '09:00', end_time: '10:00', status: 'completed' },
    ],
  },
  {
    id: '10',
    name: 'William Anderson',
    email: 'w.anderson@email.com',
    phone: '+1 (555) 012-3456',
    company_name: '',
    address: '741 Ash Lane',
    city: 'Boston',
    country: 'USA',
    budget: 2000,
    preferences: 'Cycling, Spin classes',
    notes: 'Training for triathlon',
    createdAt: '2024-10-10T16:45:00Z',
    updatedAt: '2024-11-20T14:20:00Z',
    totalValue: 1100.00,
    bookingsCount: 11,
    status: 'active',
    totalSessions: 15,
    sessionsUsed: 8,
    sessionsRemaining: 7,
    allergies: '',
    deals: [
      { id: '16', name: 'Spin Class Package', value: 800, status: 'closed' },
      { id: '17', name: 'Triathlon Training', value: 300, status: 'closed' },
    ],
    client_notes: [
      { id: '15', note: 'Triathlon in April - focus on endurance.', created_at: '2024-10-15T08:00:00Z', created_by: 'user_7', profiles: { first_name: 'Chris', last_name: 'Cycling' } },
      { id: '16', note: 'Bike fitting completed - adjusted seat height.', created_at: '2024-11-05T14:00:00Z', created_by: 'user_7', profiles: { first_name: 'Chris', last_name: 'Cycling' } },
    ],
    bookings: [
      { id: 'b21', title: 'Spin Class', schedule_date: '2025-01-09', start_time: '17:00', end_time: '18:00', status: 'scheduled' },
      { id: 'b22', title: 'Endurance Training', schedule_date: '2025-01-12', start_time: '08:00', end_time: '10:00', status: 'scheduled' },
      { id: 'b23', title: 'Spin Class', schedule_date: '2024-11-28', start_time: '17:00', end_time: '18:00', status: 'completed' },
    ],
  },
];
