import { RevenueRecord, RevenueMetrics } from './type';

export const mockRevenue: RevenueRecord[] = [
  {
    id: '1',
    amount: 89.99,
    package_type: 'Monthly Unlimited',
    payment_type: 'card',
    created_at: '2025-12-04T10:30:00Z',
    client_id: 'c1',
    clients: { name: 'Maria Papadopoulos' },
  },
  {
    id: '2',
    amount: 250.00,
    package_type: 'Quarterly Premium',
    payment_type: 'card',
    created_at: '2025-12-03T14:15:00Z',
    client_id: 'c2',
    clients: { name: 'Nikos Georgiou' },
  },
  {
    id: '3',
    amount: 15.00,
    package_type: 'Single Session',
    payment_type: 'cash',
    created_at: '2025-12-03T09:45:00Z',
    client_id: 'c3',
    clients: { name: 'Elena Stavrou' },
  },
  {
    id: '4',
    amount: 89.99,
    package_type: 'Monthly Unlimited',
    payment_type: 'card',
    created_at: '2025-12-02T16:20:00Z',
    client_id: 'c4',
    clients: { name: 'Dimitris Kosta' },
  },
  {
    id: '5',
    amount: 450.00,
    package_type: 'Annual Basic',
    payment_type: 'card',
    created_at: '2025-12-02T11:00:00Z',
    client_id: 'c5',
    clients: { name: 'Sofia Alexandrou' },
  },
  {
    id: '6',
    amount: 89.99,
    package_type: 'Monthly Unlimited',
    payment_type: 'transfer',
    created_at: '2025-12-01T08:30:00Z',
    client_id: 'c6',
    clients: { name: 'Yannis Nikolaou' },
  },
  {
    id: '7',
    amount: 30.00,
    package_type: '5 Session Pack',
    payment_type: 'cash',
    created_at: '2025-11-30T17:45:00Z',
    client_id: 'c7',
    clients: { name: 'Anna Michaelides' },
  },
  {
    id: '8',
    amount: 89.99,
    package_type: 'Monthly Unlimited',
    payment_type: 'card',
    created_at: '2025-11-29T12:10:00Z',
    client_id: 'c8',
    clients: { name: 'Kostas Papanikolaou' },
  },
  {
    id: '9',
    amount: 750.00,
    package_type: 'Annual Premium',
    payment_type: 'card',
    created_at: '2025-11-28T15:30:00Z',
    client_id: 'c9',
    clients: { name: 'Christina Vasilou' },
  },
  {
    id: '10',
    amount: 15.00,
    package_type: 'Single Session',
    payment_type: 'cash',
    created_at: '2025-11-27T10:00:00Z',
    client_id: 'c10',
    clients: { name: 'Petros Andreou' },
  },
  {
    id: '11',
    amount: 250.00,
    package_type: 'Quarterly Premium',
    payment_type: 'card',
    created_at: '2025-11-26T14:45:00Z',
    client_id: 'c1',
    clients: { name: 'Maria Papadopoulos' },
  },
  {
    id: '12',
    amount: 89.99,
    package_type: 'Monthly Unlimited',
    payment_type: 'transfer',
    created_at: '2025-11-25T09:20:00Z',
    client_id: 'c11',
    clients: { name: 'Alexandros Theodorou' },
  },
];

export const mockMetrics: RevenueMetrics = {
  daily: 339.99,
  monthly: 2309.95,
  yearly: 28450.50,
  total: 45890.25,
  topClients: [
    { name: 'Maria Papadopoulos', total: 1250.00 },
    { name: 'Sofia Alexandrou', total: 980.00 },
    { name: 'Nikos Georgiou', total: 750.00 },
    { name: 'Christina Vasilou', total: 750.00 },
    { name: 'Dimitris Kosta', total: 540.00 },
  ],
};

